### ISSUE TITLE
ScrollManager记录的position较大概率出现错误

### ISSUE THREAD

**Issue by jefshi** [ryanlijianchang/Recyclerview-Gallery#10]
问题：注册 RecyclerView.OnScrollListener 后，滚动停止后，通过 GalleryRecyclerView.getScrolledPosition(); 方法获取的当前position错误，最后导致获取数据时越界错误

再现：反复滑动页面，貌似要慢点滑动
LogCat：如下，每行末尾是 GalleryRecyclerView.getScrolledPosition(); 的值

04-28 10:33:50.620 25434-25434/com.nijigenlink.gb E/--[BoostFragment$1][onScrollStateChanged]: 2
04-28 10:33:50.637 25434-25434/com.nijigenlink.gb E/--[BoostFragment$1][onScrollStateChanged]: 2
04-28 10:33:52.123 25434-25434/com.nijigenlink.gb E/--[BoostFragment$1][onScrollStateChanged]: 0
04-28 10:33:52.140 25434-25434/com.nijigenlink.gb E/--[BoostFragment$1][onScrollStateChanged]: 0
04-28 10:33:52.327 25434-25434/com.nijigenlink.gb E/--[BoostFragment$1][onScrollStateChanged]: 0
04-28 10:33:53.254 25434-25434/com.nijigenlink.gb E/--[BoostFragment$1][onScrollStateChanged]: 1
04-28 10:33:53.541 25434-25434/com.nijigenlink.gb E/--[BoostFragment$1][onScrollStateChanged]: 1
04-28 10:33:54.217 25434-25434/com.nijigenlink.gb E/--[BoostFragment$1][onScrollStateChanged]: 0
04-28 10:33:54.234 25434-25434/com.nijigenlink.gb E/--[BoostFragment$1][onScrollStateChanged]: 0
04-28 10:33:56.345 25434-25434/com.nijigenlink.gb E/--[BoostFragment$1][onScrollStateChanged]: 0
04-28 10:33:58.050 25434-25434/com.nijigenlink.gb E/--[BoostFragment$1][onScrollStateChanged]: 3
04-28 10:33:58.367 25434-25434/com.nijigenlink.gb E/AndroidRuntime: FATAL EXCEPTION: main
                                                                    Process: com.nijigenlink.gb, PID: 25434
                                                                    java.lang.IndexOutOfBoundsException: Index: 3, Size: 3
                                                                        at java.util.ArrayList.get(ArrayList.java:411)
                                                                        at com.nijigenlink.gb.ui.boost.BoostAdapter.getItem(BoostAdapter.java:38)
                                                                        at com.nijigenlink.gb.ui.boost.BoostFragment$1.onScrollStateChanged(BoostFragment.java:79)
                                                                        at android.support.v7.widget.RecyclerView.dispatchOnScrollStateChanged(RecyclerView.java:4759)
                                                                        at android.support.v7.widget.RecyclerView.setScrollState(RecyclerView.java:1434)
                                                                        at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:4908)
                                                                        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:933)
                                                                        at android.view.Choreographer.doCallbacks(Choreographer.java:742)
                                                                        at android.view.Choreographer.doFrame(Choreographer.java:671)
                                                                        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:919)
                                                                        at android.os.Handler.handleCallback(Handler.java:761)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                        at android.os.Looper.loop(Looper.java:156)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6595)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

**Comment by ryanlijianchang** [comment]
感谢提出的修改
